source 'https://rubygems.org'
gem 'sinatra', '~> 1.3'
gem 'rubylet-rack', :path => '../../../..', :require => false
gem 'rubylet-rack-handler', :path => '../../../../../rubylet-rack-handler', :require => false

