require 'rake/version_task'
require 'rubygems/package_task'

def gemspec
  unless @gemspec
    file = File.expand_path(File.join(__FILE__, '../rack-handler-rubylet-jetty.gemspec'))
    @gemspec = Gem::Specification.load(file)
  end

  @gemspec
end

Rake::VersionTask.new

Gem::PackageTask.new(gemspec) do |p|
  p.gem_spec = gemspec
end
