require 'rake/testtask'
require 'rake/version_task'
require 'rubygems/package_task'

def gemspec
  unless @gemspec
    @gemspec = Gem::Specification.load(Dir.glob('*.gemspec').first)
  end

  @gemspec
end

namespace :test do
  Rake::TestTask.new(:spec) do |t|
    t.pattern = 'spec/**/*_spec.rb'
    t.libs.push 'spec'
  end

  Rake::TestTask.new(:integration) do |t|
    t.pattern = 'test/it/**/*_it.rb'
    t.libs.push 'test/it'
  end
end

task :test => 'test:spec'
task :spec => 'test:spec'

Rake::VersionTask.new

Gem::PackageTask.new(gemspec) do |p|
  p.gem_spec = gemspec
end
