source 'https://rubygems.org'
gem 'rack', '= 1.4.1'
gem 'rubylet-rack', :path => '../../../..', :require => false
gem 'rubylet-rack-handler', :path => '../../../../../rubylet-rack-handler', :require => false

