require 'rake/testtask'
require 'rake/version_task'
require 'rubygems/package_task'

def gemspec
  unless @gemspec
    @gemspec = Gem::Specification.load(Dir.glob('*.gemspec').first)
  end

  @gemspec
end

namespace :test do
  Rake::TestTask.new(:spec => :compile) do |t|
    t.pattern = 'spec/**/*_spec.rb'
    t.libs.push 'spec'
  end

  Rake::TestTask.new(:integration => :compile) do |t|
    t.pattern = 'test/it/**/*_it.rb'
    t.libs.push 'test/it'
  end
end

task :test => 'test:spec'
task :spec => 'test:spec'
task :default => :test

Rake::VersionTask.new

ext = File.expand_path('../ext', __FILE__)
ext_jar = File.expand_path('../lib/rubylet/rack/ext.jar', __FILE__)

file ext_jar => Dir[File.join(ext, 'src/main/java/**/*.java')] do
  Dir.chdir(ext) do
    system 'mvn verify'
  end
end

task :compile => ext_jar

Gem::PackageTask.new(gemspec) do |p|
  p.gem_spec = gemspec
end
task :package => ext_jar
