source 'https://rubygems.org'
gem 'rubylet-rack', :path => '../../../..', :require => false
gem 'rails', '~> 3.0.0'
gem 'jruby-openssl'
gem 'json'

# used for development
gem 'rubylet-rack-handler', :path => '../../../../../rubylet-rack-handler', :require => false
