source 'http://rubygems.org'
gem 'rails', '~> 3.1.0'
gem 'rubylet-rack', :path => '../../../..', :require => false

# used for development
gem 'rubylet-rack-handler', :path => '../../../../../rubylet-rack-handler', :require => false
