require 'rake/testtask'
require 'rake/version_task'
require 'rubygems/package_task'
require 'uri'

def gemspec
  @gemspec ||= Gem::Specification.load('.gemspec')
end

Rake::TestTask.new(:test) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  t.libs.push 'spec'
end

task :spec => :test

Rake::VersionTask.new

Gem::PackageTask.new(gemspec) do |p|
  p.gem_spec = gemspec
end
